comment:
  image:
    repository: ysavchen/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: ysavchen/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: ysavchen/ui
    tag: latest
  service:
    externalPort: 9292
